from pydantic import BaseModel
from typing import Optional

class DocState(BaseModel):
    org_logo_url: Optional[str] = ""
    meeting_date: Optional[str] = ""
    staff_member_name: Optional[str] = ""
    staff_member_designation: Optional[str] = ""
    staff_member_email: Optional[str] = ""
    staff_member_phone: Optional[str] = ""
    staff_member_extension: Optional[str] = ""
    application_number: Optional[str] = ""
    location: Optional[str] = ""
    application_name: Optional[str] = ""
    zoning_district: Optional[str] = ""
    use_classification: Optional[str] = ""
    project_description: Optional[str] = ""


    # Fields generated by agents
    land_use_permits_content: Optional[str] = ""
    commercial_standards_content: Optional[str] = ""
    general_standards_content: Optional[str] = ""
    zoning_content: Optional[str] = ""

    # Final document after postprocessing
    final_document: Optional[str] = ""